### ISSUE TITLE
Add default Craft plugins

### ISSUE THREAD

**Issue by angusfretwell** [angusfretwell/generator-craftsman#13]
Suggestions:
- [Inspector](https://github.com/adrianmacneil/craft-inspector)
- [Contact Form](https://github.com/pixelandtonic/ContactForm/)
- [Truncate](https://github.com/nizur/Truncate)
- [Active](http://sprout.barrelstrengthdesign.com/craft-plugins/active)
- [Email field](http://sprout.barrelstrengthdesign.com/craft-plugins/email-field)
- [LinkIt](https://github.com/fruitstudios/LinkIt)
- [Wordcount](https://github.com/aelvan/RedactorWordCount-Craft/)
- [Simple Sitemap](https://github.com/xodigital/SimpleSitemap)
- [Smartmap](https://github.com/lindseydiloreto/craft-smartmap)
- [GroupBy](https://github.com/timkelty/groupby-craft)

**Comment by angusfretwell** [comment]
Cheat-sheet (contextual templating examples):
https://github.com/focuslabllc/craft-field-cheat-sheet

**Comment by mathollingsworth** [comment]
The https://github.com/focuslabllc/craft-field-cheat-sheet cheat sheet template should be restyled to Francis Bond branding. ```php_value   xdebug.max_nesting_level 1000```also needs to be added to .htaccess
